// Code generated by goctl. DO NOT EDIT.
package types

type AddRoundRequest struct {
	Name string `json:"name"`
}

type Round struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status,options=RUNNING|FINISHED"`
	ISCurrent bool   `json:"is_current"`
}

type ListRoundsResp struct {
	Rounds []Round `json:"rounds"`
}

type Bib struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status,options=RUNNING|FINISHED"`
	ISCurrent bool   `json:"is_current"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	Duration  string `json:"duration"`
}

type GetRoundRequest struct {
	ID string `path:"id"`
}

type UpdateRoundRequest struct {
	Name string `json:"name"`
}

type DeleteRoundRequest struct {
	Round string `path:"round"`
}

type AddBibRequest struct {
	Round string `path:"round"`
	Bib   string `json:"bib"`
}

type GetBibRequest struct {
	Round string `path:"round"`
	Bib   string `path:"bib"`
}

type DeleteBibRequest struct {
	Round string `path:"round"`
	ID    string `path:"id"`
}

type SetRoundCurrentRequest struct {
	Round string `path:"round"`
}

type SetBibStatusRequest struct {
	Round  string `path:"round"`
	Status string `path:"status" json:"status,options=RUNNING|FINISHED"`
}

type SetBibCurrentRequest struct {
	Round string `path:"round"`
	Bib   string `path:"bib"`
}

type GetCurrentBibReq struct {
	Round string `path:"round"`
}

type GetCurrentBibResp struct {
	CurrentBib string `json:"current_bib"`
}

type ListBibsReq struct {
	Round string `path:"round"`
}

type ListBibsResp struct {
	Bibs []Bib `json:"bibs"`
}

type GetCurrentRoundResp struct {
	CurrentRound string `json:"current_round"`
}
